### ISSUE TITLE
Adding the regex for all the rules

### ISSUE THREAD

**Issue by RavinduWeerakoon** [RavinduWeerakoon/R_pal#1]
In the lexical analyzer, I added regex rules for identifiers, integers, and spaces. Please add rules for other elements.

**Comment by lckariyawasam** [comment]
Added the rules for the other elements in #[36bb0d2](https://github.com/RavinduWeerakoon/R_pal/commit/36bb0d2aeb793dc584b517f584accd455af99a02)
